# Generated by Django 2.2.4 on 2020-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_insta_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emails',
            field=models.IntegerField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
