# Generated by Django 2.2 on 2020-04-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200404_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='instaimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='temp', verbose_name='Image for Instagram')),
            ],
        ),
    ]
