# Generated by Django 2.2 on 2020-04-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0007_auto_20200408_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaimg',
            name='img',
            field=models.ImageField(default=None, upload_to='temp', verbose_name='Image for Instagram'),
        ),
        migrations.CreateModel(
            name='email_handle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
