# Generated by Django 2.2 on 2020-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20200411_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insta_handle',
            name='code',
        ),
        migrations.AddField(
            model_name='twitter_handle',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='twitter_handle',
            name='password',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
